const ENV_AUTH_NOT_REQUIRED = false;
const ENV_CLIENT_ID = 'OAUTH_CLIENT_ID_PLACEHOLDER';
const ENV_REDIRECT_URI = 'OAUTH_REDIRECT_URI_PLACEHOLDER';
const ENV_API_HOST = 'API_HOST_PLACEHOLDER';
const ENV_API_PROTOCOL = 'API_PROTOCOL_PLACEHOLDER';

export { ENV_API_HOST, ENV_API_PROTOCOL, ENV_AUTH_NOT_REQUIRED, ENV_CLIENT_ID, ENV_REDIRECT_URI };
