name: Frontend Automatic testing

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      workdir: ./frontend
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
        working-directory: ${{env.workdir}}
      - name: Run linter
        run: npm run lint
        working-directory: ${{env.workdir}}
      - name: Run tests
        run: npm t
        working-directory: ${{env.workdir}}
